### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by arunisaac** [tom-tan/cwl-mode#1]
Hi,

Could you tag releases 0.2.1 and maybe 0.2.2 as well?

Thanks!

**Comment by tom-tan** [comment]
I found that I made tags `0.2.1`..`0.2.5` but they were not released :-(
I released [0.2.5](https://github.com/tom-tan/cwl-mode/releases/tag/0.2.5).
Thanks!

**Comment by arunisaac** [comment]
Thanks for the quick response! You might also want to update the version
on line 5 of cwl-mode.el.

**Comment by tom-tan** [comment]
I updated the version string in cwl-mode.el and released 0.2.6.
Thanks!
